name: Push builds

on:
  push:
    branches:
      - gd4
      - main

jobs:
  build-web:
    uses: ./.github/workflows/build-game-4.0.2.yml
    with:
      platform: Web
      name: sxgd-kitchen-sink
      output_name: index.html