name: Push builds

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-web:
    uses: ./.github/workflows/build-game.yml
    with:
      platform: HTML5
      name: sxgd-kitchen-sink
      output_name: index.html