name: Push builds

on:
  push:
    branches:
      - ci-force-main
      - godot-3.x
      - main

jobs:
  build-web-godot-3:
    if: ${{ github.ref_name == 'godot-3.x' }} 
    uses: Srynetix/godot-github-workflows/.github/workflows/build-game-3.5.1.yml@main
    with:
      platform: HTML5
      name: sxgd-kitchen-sink
      output_name: index.html

  build-web-main:
    if: ${{ github.ref_name == 'main' }} 
    uses: Srynetix/godot-github-workflows/.github/workflows/build-game-4.0.2.yml@main
    with:
      platform: Web
      name: sxgd-kitchen-sink
      use_main_folder: true
      output_name: index.html