name: Push builds

on:
  push:
    branches:
      - gd4
      - main

jobs:
  build-web:
    uses: ./build-game-4.0.2.yml@gd4
    with:
      platform: HTML5
      name: sxgd-kitchen-sink
      output_name: index.html